src/components/BillStatusTag/BillStatusTag.story.svelte, src/components/BillStatusTag/BillStatusTag.svelte
Now finished. Please check :D
Related to #21
=> ptsgrn/#21 BillStatusTag Component

src/components/BillCard/BillCard.story.svelte, src/components/BillCard/BillCard.svelte
see: https://github.com/wevisdemo/parliament-watch/issues/26
=> takeshikriang / #26 Add BillCard component

src/components/NavigationBar/NavigationBar.svelte, src/components/NavigationBar/NavigationPane.svelte, src/routes/+layout.svelte
=> Fix for NavigationBar overflow & flickering slide effect while scrolling down

.gitignore, package.json, src/components/NavigationBar/NavigationBar.svelte, src/components/NavigationBar/SearchInput.svelte, src/components/SearchResult/SearchResult.story.svelte, src/components/SearchResult/SearchResult.svelte, src/components/SearchResultGroup/HightlightText.svelte, src/components/SearchResultGroup/NoResultItemsFound.svelte, src/components/SearchResultGroup/ResultItem.story.svelte, src/components/SearchResultGroup/ResultItem.svelte, src/components/SearchResultGroup/SearchResultGroup.story.svelte, src/components/SearchResultGroup/SearchResultGroup.svelte, src/libs/__test___/search.test.ts, src/libs/search.ts, src/models/search.ts, yarn.lock
This pull request for adding search function.
=> #34 navigationbar search function

README.md
Typos & minor fix on proper denomination: lines 98, 129, 144
=> Fixes in documentation: README.MD

src/components/LegislativeProcess/Sidebar.svelte, src/routes/legislative-process/+page.svelte
For #53 
- I cannot highlight the nav header as shown in #53 or this [Figma](https://www.figma.com/file/cdtZnPegHm5CGHWqIND5Im/Design_Phase01?type=design&node-id=412-164715&mode=dev) because the `SideNavMenu` component does not have a `isSelected` prop, only `SideNavMenuItem` has it.
- I also made the Sidebar sticky, because otherwise users will not be able to see the active section in the Sidebar anyways.
Feel free to comment/give feedbacks. This is my first time writing Svelte 😃.
=> Highlight active section on scroll in legistrative process sidebar

src/components/Assemblies/CabinetChart.svelte, src/components/Assemblies/CabinetRole.svelte, src/components/Assemblies/LowerHouseSummary.svelte, src/components/Assemblies/SummaryTotal.svelte, src/components/Assemblies/shared.ts, src/routes/assemblies/[id]/+page.server.ts, src/routes/assemblies/[id]/+page.svelte
=> Support cabinet in assembly's summary

src/components/CabinetMembers/CabinetMembers.svelte, src/components/CabinetMembers/CabinetProfile.svelte, src/components/CabinetMembers/MinistryGroup.svelte, src/components/PoliticianProfile/PoliticianProfile.svelte, src/routes/assemblies/[id]/+page.svelte
=> Add cabinet member section in assembly page

src/components/Assemblies/LastestBills.svelte, src/components/Assemblies/RoleChanges/RoleChangeItem.svelte, src/routes/assemblies/[id]/+page.svelte
=> Add latest bills section for cabinet in assembly page

src/components/Assemblies/Summary.svelte, src/components/Assemblies/SummaryGroup.svelte, src/routes/assemblies/[id]/+page.svelte
=> Update SummaryGroup component in assembly page

src/components/Assemblies/RoleChanges/RoleChangeGroup.svelte, src/routes/assemblies/[id]/+page.server.ts, src/routes/assemblies/[id]/members/[groupby]/groupby.ts
=> Use correct changes and latest bills data

src/components/Assemblies/SeatChart.svelte
=> Fix reactive statement to redraw when props change

src/lib/datasheets/assembly-member.ts, src/routes/assemblies/[id]/members/[groupby]/+layout.server.ts, src/routes/assemblies/[id]/members/[groupby]/+page.server.ts, src/routes/assemblies/[id]/members/[groupby]/+page.svelte, src/routes/assemblies/[id]/members/[groupby]/groupby.ts
=> Support assembly's members page for cabinet

src/components/PromiseList/PromiseCard.svelte, src/components/PromiseList/PromiseList.svelte, src/routes/promises/+page.svelte, src/routes/promises/explore/+page.server.ts, src/routes/promises/explore/+page.svelte
=> Create Explore Page

src/routes/about/+page.svelte
It is Creative Commons Attribution-NonCommercial-ShareAlike  not Creative Commons Attribution-ShareAlike License because It can't commercial use. "สามารถนำไปเผยแพร่และดัดแปลงได้ โดยต้องระบุที่มา แต่ห้ามนำไปใช้เพื่อการค้า และต้องเผยแพร่งานดัดแปลงโดยใช้สัญญาอนุญาตชนิดเดียวกัน"
=> Change the license in about page

src/components/DataPage/DataPage.story.md, src/components/DataPage/DataPage.story.svelte, src/components/DataPage/DataPage.svelte, src/components/LegislativeProcess/BillStatusCard.svelte, src/routes/bills/explore/+page.svelte
=> fix: remove text from all bill status cards and change text in data page

src/components/PromiseList/PromiseCard.svelte
=> fix: change text for promise card

src/components/NavigationBar/NavigationBar.svelte, src/components/NavigationBar/SideMenuLink.svelte, src/components/PromiseList/PromiseList.story.svelte
Close #151 
- Make the sidebar on mobile close when the user clicks on a menu list.
[379742950-83318469-9c03-4d83-a857-6f5886b2278a.webm](https://github.com/user-attachments/assets/aaa2425d-08af-4b77-8bc5-68991c904ed0)
https://github.com/user-attachments/assets/7f0d4b8f-9b79-4dfa-b226-a571bb5c596e
=> fix navbar on mobile does not close when changing to new page

src/components/PromiseDetail/PromiseProgressTimeline.svelte, src/lib/datasheets/fetchers/global-events.ts, src/lib/datasheets/index.ts, src/models/global-event.ts, src/routes/promises/[id]/+page.server.ts, src/routes/promises/[id]/+page.svelte
- Add global events in Promise Details page
=> Promise global events

src/components/DataPage/DataPage.story.svelte, src/components/DataPage/DataPage.svelte, src/components/LinkTable/LinkTable.svelte, src/routes/assemblies/[id]/votes/+page.svelte, src/routes/bills/explore/+page.server.ts, src/routes/bills/explore/+page.svelte, src/routes/politicians/[id]/votes/+page.svelte, src/routes/votings/[id]/votes/+page.svelte
Close #163 
- Decouple model in LinkTable and DataPage
- Debug duplicate key(id)  in filteredData 
Pages that use this component
=> refactor: decouple model in LinkTable and DataPage

src/routes/+layout.svelte
Close #173 
- Add canonical link to every page when in production
=> feat: add canonical link

src/routes/assemblies/[id]/votes/+page.svelte
Close #185
- fix mispelling from ผลลัพท์ to ผลลัพธ์
=> patch: fix mispelling from ผลลัพท์ to ผลลัพธ์
