wevisdemo/parliament-watch

- package.json
- src/components/votes/VoteCard.story.svelte
- src/components/votes/VoteCard.svelte
- src/mocks/data/voting.ts
- src/routes/assemblies/[id]/+page.svelte
- src/routes/assemblies/[id]/+page.ts
- src/routes/politicians/[id]/+page.svelte
- tailwind.config.js
- yarn.lock
> fResult/#5 VoteCard Component

- src/routes/legislative-process/+page.svelte
Related to #20.
This PR intended to add legislative process heading text and their styles according to this [Figma design](https://www.figma.com/file/cdtZnPegHm5CGHWqIND5Im/Design_Phase01?type=design&node-id=319-155076&mode=dev).
Note that: I set `max-width` equals to 800px as same as this design's body width on desktop size, but not sure if we have any specific breakpoint.
Example
---
Viewport of 320px width.
---
Viewport of 800px width.
---
Viewport of 1024px width.
> Icyscools/#20 Add Legislative Process Page: Body Skeleton

- src/components/Proposer/Proposer.story.svelte
- src/components/Proposer/Proposer.svelte
- src/mocks/data/politician.ts
- Implemented `Proposer` for normal screen and mobile screen.
- `Proposer` supports 3 types of proposer, which is seperated to 3 properties. (I think union types up to 1 with type guard is too complicated. 🤮)
- `Politician` as party, from Figma I found out that it is also requires `Assembly` (สส. ชุดที่ xxx) in order to make it complete. I've packed 3 things up as `PartyPolitician`
- `Assembly`
- Other proposers as `CommonProposer` with `name` and `description`
> Badgooooor/#29 Proposer component

- src/components/DataPage/DataPage.svelte
- src/components/NavigationBar/SideMenuPane.svelte
Fixes #38 
- The filter button now have `interactive-01` color (with the default filter, or `interactive-02` color otherwise) 
(Using `class` attributes because tailwind force transparent background on button)
- The filter button is now behind the sidebar
- The filter panel is now behind the navigation bar on mobile screen size
- On desktop, The filter input (top part of the filter panel) will now aware of navigation bar position (or more accurately, it will leave a space on top when scroll up to prevent itself from being hidden behind navigation bar)
[Kapture 2023-10-22 at 20.08.29.webm](https://github.com/wevisdemo/parliament-watch/assets/29707893/a057a15e-ce4f-494c-8193-29e17f28f1a0)
[Kapture 2023-10-22 at 20.19.09.webm](https://github.com/wevisdemo/parliament-watch/assets/29707893/c6a0 …
> Fix #38 Incorrect DataPage's filter and NavigationBar z-index alignment

- src/app.html
- src/routes/+layout.svelte
- src/routes/about/+page.server.ts
- src/routes/about/+page.svelte
- src/routes/assemblies/[id]/+page.server.ts
- src/routes/assemblies/[id]/+page.svelte
- src/routes/assemblies/[id]/members/[groupby]/+page.server.ts
- src/routes/assemblies/[id]/members/[groupby]/+page.svelte
- src/routes/assemblies/[id]/votes/+page.server.ts
- src/routes/assemblies/[id]/votes/+page.svelte
- src/routes/bills/[id]/+page.server.ts
- src/routes/bills/[id]/+page.svelte
- src/routes/legislative-process/+page.server.ts
- src/routes/legislative-process/+page.svelte
- src/routes/politicians/[id]/+page.server.ts
- src/routes/politicians/[id]/+page.svelte
- src/routes/politicians/[id]/votes/+page.server.ts
- src/routes/politicians/[id]/votes/+page.svelte
- src/utils/seo.ts
From a common pattern in [the documentation](https://kit.svelte.dev/docs/seo#manual-setup-title-and-meta), I've moved SEO-related tags into the main `+layout.svelte` and return the formatted SEO data from each page's `+page.ts`. To make formatting easier, I've created a helper function called `createSeo()` to help you properly format the SEO data.
> Proper Handling SEO tags

- src/routes/assemblies/[id]/votes/+page.svelte
Try to resolve this issue https://github.com/wevisdemo/parliament-watch/issues/93
Since the `title` field can be null unlike `nickname` field in https://docs.google.com/spreadsheets/d/1SbX2kgAGsslbhGuB-EI_YdSAnIt3reU1_OEtWmDVOVk/edit?gid=982824090#gid=982824090
> Using nickname field instead of nullable title field in voting page

- src/components/DataPage/DataPage.svelte
- src/routes/assemblies/[id]/votes/+page.svelte
- src/routes/bills/explore/+page.svelte
Resolves https://github.com/wevisdemo/parliament-watch/issues/115
What I did:
- Adjust page size to 50 for `votings` and `bills` page
- I found that the id of some data can crash resulting in the error `Error: Cannot have duplicate keys in a keyed each:` so I map those the data in `DataTable` and give them a unique id to prevent crashing
> Make votings and bills tables show 50 items per page

- src/routes/votings/[id]/+page.svelte
Resolves https://github.com/wevisdemo/parliament-watch/issues/114
**What I did**
- Added mappings for missing colors
> Display invalid status label color in some voting page

- src/components/PromiseDetail/PromiseClarificationAnswer.svelte
- src/components/PromiseDetail/PromiseClarificationLog.svelte
- src/components/PromiseList/ClarificationLog.svelte
- src/routes/promises/[id]/+page.svelte
resolve #102 
It's still WIP but creating this just to list out questions that I have. But feel free to leave out any comment on the code na kub, i'm still not very familiar with the codebase, so there might be something reusable that i miss.
Feature-related questions:
1. it seems like we want to show a clarification log a different way, depends on whether the clarification answer is "good enough". do we have this "good-enough status" in our data model yet?
Development questions:
1. i got a lot of errors running svelte check in pre-push. not sure what i did wrong.
2. i got this error when running the web and it's causing the whole thing to go `500`
and the cause seems to be because the `safeFind` is not really safe and still throws an error?
> feat(promise): promise detail - clarification logs

- src/components/Assemblies/AssemblyTooltip.svelte
- src/components/Assemblies/CabinetRole.svelte
- src/components/Assemblies/SeatChart.svelte
- src/components/Assemblies/SummaryTotal.svelte
- src/components/Assemblies/shared.ts
- src/routes/assemblies/[id]/+page.server.ts
close #116 
- Add tooltips for Assembly, Parliament and Senate members
- Adjust some type to include members list data
> feat: add tooltips in assembly member chart

- src/components/Promise/Home/PromiseMovementSection.svelte
- src/components/Promise/Home/PromiseStatusCard.svelte
Close #133 #134 
- Add `if` condition for displaying promise status in PromiseMovementSection
- Add `if` condition for displaying promise samples and `See All` button in PromiseStatusCard
> feat: do not display an empty promise status or button

- src/components/Promise/Home/AboutCard.svelte
- src/components/Promise/Home/AboutSection.svelte
- src/routes/promises/+page.server.ts
- src/routes/promises/+page.svelte
Close #130 #131 #132 
- add filed avatar in prime minister for display in cabinet info (issue 130)
- display numbers of ministers of the parties (issue 131)
- add previous cabinet information (issue 132)
before:
after:
> fix: cabinet info

- src/components/Assemblies/AssemblyTooltip.svelte
- Center tooltip's position
- Check screen boundary and adjust tooltip's position to display within screen
> fix: tooltip partially missing in small screen

- src/components/PromiseList/PromiseList.story.svelte
Close #121 
- Add a story for PromiseList component
- In story create control for summaries props each summary showing out different time and status so that PromiseList can show behaviors like sorting and list view from different time and status.
> feat: add story to PromiseList component

- .github/workflows/staging.yml
Close #141 
- Changed the `deploy-to-staging` step in `.github/workflows/staging.yml` to use `cloudflare/wrangler-action@v3` instead of   the deprecated `cloudflare/pages-action@v1`
_**Note:** With this change, we will lose the [deployments records](https://github.com/wevisdemo/parliament-watch/deployments) as it is not yet supported by this wrangler action. (It is mentioned in the wrangler's [repo README](https://github.com/cloudflare/pages-action?tab=readme-ov-file) and this [issue](https://github.com/cloudflare/wrangler-action/issues/301))_
_N/A_
- Could you temporarily set the [staging workflow](https://github.com/wevisdemo/parliament-watch/actions/workflows/staging.yml) to run on this branch? As I cannot test it on my forked repo because it requires secrets
> fix: migrate away from cloudflare-pages action as it is deprecated

- src/components/PromiseDetail/PromiseStatusModal.svelte
- src/components/PromiseDetail/PromiseStatusTag.story.svelte
- src/components/PromiseDetail/PromiseStatusTag.svelte
- src/components/SearchResult/SearchResult.story.svelte
- src/components/SearchResult/SearchResult.svelte
- src/components/SearchResultGroup/ResultItem.svelte
- src/models/search.ts
- src/routes/promises/[id]/+page.svelte
Close #129 
- Make `<SearchResult />` component support showing promises as a group
- Show the `<PromiseStatusTag />` in the promise result item as well. (It's not mentioned in the issue, but I saw in [Figma](https://www.figma.com/design/cdtZnPegHm5CGHWqIND5Im/Design_Phase01?node-id=1112-347880&t=K1TpUqlPWlJpZKPX-1) that it has a tag)
- Update `<PromiseStatusTag />` to support showing small text so that it can be used in both the PromiseCard and this search result item
> feat: show promises in search results component

- src/components/Index/SectionMenuItem.svelte
I noticed that the arrow in the section menu items was misaligned on mobile or small screens.
So, I added a `width: 100%` style, `w-full` to push the arrows to the right side of the screen, ensuring proper alignment.
* Before
* After
---
If you have any feedback or suggestions, please let me know.
> fix: update SectionMenuItem on mobile

- src/components/BillCard/BillCard.svelte
- src/components/Proposer/Proposer.story.svelte
- src/components/Proposer/Proposer.svelte
- src/lib/model-component-adapters/bill-proposer.ts
- src/models/politician.ts
- src/routes/bills/[id]/+page.svelte
Close #167 
- Define models used in this share component
- Pull out assembly role lookup at specific time to Politician model
- Add two more variants in story
- Export prop types for future usages
- Feedback on the BIG politician prop.
- Should I introduce an interim function as an adapter from `Bill` to the component's props? Since this will be bubble up in `<BillCard>` too.
> Refactor <Proposer> by pulling out model imports

- src/components/PromiseList/PromiseCard.story.svelte
- src/components/PromiseList/PromiseCard.svelte
- src/components/PromiseList/PromiseList.svelte
Close #166
- Remove the models import from `PromiseList` and `PromiseCard`.
- Define the `PromiseSummary` type in `PromiseCard`.
- Use svelte's `ComponentProps` to extract the summary type in `PromiseList`
- FYI, I didn't include color in the party field because I found no usage for it.
This is my first PR here. Please let me know if anything needs improvement or changes.
> refactor: Decouple models from PromiseList and PromiseCard

- src/components/BillCard/BillCard.story.svelte
- src/components/BillCard/BillCard.svelte
- src/components/Index/BillContent.svelte
- src/components/bills/Progress.svelte
- src/routes/bills/+page.svelte
Close #162
- Decouple model from `BillCard`
- Note: Currently left `bill` props in `BillCard` due to currently depended on `Proposer` which will be refactored in issue #167, I added `TODO` for that issue though.
> Decouple model from BillCard

- src/components/Index/VotingContent.svelte
- src/components/PromiseDetail/PromiseProgressTimeline.svelte
- src/components/VoteCard/VoteCard.story.svelte
- src/components/VoteCard/VoteCard.svelte
- src/components/bills/Progress.svelte
- src/lib/datasheets/voting.ts
- src/lib/model-component-adapters/votecardvoting.ts
- src/routes/+page.server.ts
- src/routes/assemblies/[id]/+page.server.ts
Close #168
- Updated the VoteCardVoting schema to combine the previously picked keys (from Voting) + HighlightedVoteByGroup, into a new type owned by the VoteCard component. The VoteCard component now takes a single VoteCardVoting prop.
- Removed the Voting type import from `/models`
- Added a `toVoteCardVoting: Voting x HighlightedVoteByGroup[] -> VoteCardVoting` convenience function for parent components
> Decouple VoteCard from model

- src/components/Index/BillContent.svelte
- src/components/LawStatusCard/LawStatusCard.svelte
- src/routes/bills/+page.server.ts
Close #164 
- Decouple LawStatusCard from model
- Update BillContent component to use LawStatusCard
> refactor: decouple LawStatusCard from model

- src/routes/bills/explore/+page.svelte
I updated the width of the `proposedOn` cell in the Bills Explore page to ensure the text stays on one line for small screen. Additionally, I removed the margin from the `BillStatusTag` to align it with the content.
* Before
* After
---
If you have any feedback or suggestions, please let me know.
> fix: bills explore table styles
